### PR TITLE
Use relative imports

### PR DESCRIPTION
**Pull request by pjz**
Per #454, moved to almost all relative imports.  The exceptions are the configuration module which was more complicated and is going away soon, and `algorithm/website.py` because I wasn't sure how relative imports would interact with the `algorithm.py` module stuff.

### CODE REVIEW

**Comment by whit537** [comment]
Looks good so far. What happens to the test suite if you update `algorithms/website.py`? Off-hand I wouldn't expect relative imports to make a difference there.

**Comment by pjz** [comment]
Test suite works with a change to relative imports - is that enough of a test that you're willing to risk it?

**Comment by pjz** [comment]
Should I add that commit to this PR or not?  It passes the tests, and if you think that's enough of a test to expose errors, then I'll push that commit to this PR/branch.  If you think it might not be a good enough test, I'll leave it off for now.

**Comment by whit537** [comment]
@pjz Ya, go ahead and push it here.

**Comment by pjz** [comment]
There ya go.

**Comment by whit537** [comment]
!m @pjz

**Pull request merged**
