### PR TITLE
sort out a complicated state/context bug

### PR DESCRIPTION
**Pull request by whit537**
Aspen 0.40 breaks the i18n machinery over on Gratipay. What's the right fix?

### CODE REVIEW

**Comment by pjz** [comment]
wow, that's just a mess, innit?  Okay, so it looks to me like maybe throwing all of `state` in as the context is just a bad idea: Too many unintended namespace collisions.  Previously we manually imported a small list of what was wanted.  Maybe it would be easier to just implement #30 and be done with it.

**Comment by whit537** [comment]
(I rebased to squash three commits on this test into one.)

Yes, it is a mess. :-(

We need to do whatever's fastest here. I believe this is the last thing holding up https://github.com/gratipay/gratipay.com/pull/3588, which is a high-priority PR.

**Comment by Changaco** [comment]
I don't think this is an Aspen bug, you **can** modify `state` from the renderer by doing `context['state']['bar'] = 'buz'`.

**Comment by whit537** [comment]
!m @Changaco 

Thanks. :-)

**Comment by whit537** [comment]
Not out of the woods yet:

https://travis-ci.org/gratipay/gratipay.com/builds/69313849

**Comment by whit537** [comment]
(Those failures were previously hidden amongst https://github.com/gratipay/gratipay.com/pull/3581.)

**Comment by whit537** [comment]
Okay, fixed in https://github.com/gratipay/gratipay.com/commit/e0109cdb52f02f1e8963849adeb42311cef2aa6c.

**Pull request closed without merging**
