### PR TITLE
switch from Website(argv) to Website(**kwargs)

### PR DESCRIPTION
**Pull request by whit537**
Builds on #381.

### CODE REVIEW

**Comment by whit537** [comment]
Calling this PR good and ready, @pjz @techtonik et al. This takes us from:

```python
from aspen import serve, website
serve(Website(['--www_root`, 'foo']))
```

to:


```python
from aspen import serve, website
serve(Website(www_root='foo'))
```

**Comment by whit537** [comment]
Closes #374.

**Comment by techtonik** [comment]
From one side I kind of liked the feature. From the other, the OptionParser dependency is huge.

**Comment by techtonik** [comment]
I mean it might be possible to preserve both.

**Comment by pjz** [comment]
nah, it's only necessary if you're configuring from the cmdline - configure from anywhere else: python, a `configparser` file, json, etc, and it would be unneeded. Choosing not to decide is the best choice here, I think.

**Pull request merged**
