### PR TITLE
port to Python 3

### PR DESCRIPTION
**Pull request by whit537**
Closes

### CODE REVIEW

**Comment by whit537** [comment]
I was surprised to find that the test suite passes under Python 3.3 on my machine. Let's see what Travis has to say ...

**Comment by whit537** [comment]
Perhaps predictably, I wasn't running the test suite under Python 3 after all, because `python` is hard-coded in `build.py`'s call out to `virtualenv`.

**Comment by whit537** [comment]
I'm outta time for now, so to make this PR more manageable I've reverted the first two commits. Now all this does is update our bootstrap deps and refactor `build.py` a bit. This brings us up to the point where we can really start testing against Python 3 once we're ready to dive into that.

**Comment by whit537** [comment]
Ready for review, @pjz et al.

**Comment by pjz** [comment]
Are you sure you can swap in `sys.executable` for `main.options.python` ? If so, you might as well get rid of the `extra_options` stuff that get passed into fabricate's `main()` function.   That's there so you can run `python build.py --python python3 test` for example.  It was previously used for jython testing (under Hudson - will AppVeyor support jython as well?

**Comment by whit537** [comment]
> `python build.py --python python3 test`

That looks goofy. Why not just `python3 build.py test`? You're saying the reason has something to do with jython?

**Comment by whit537** [comment]
> will AppVeyor support jython as well?

Well, Java runs on Windows. :P Jython support is orthogonal to OS support, no?

**Comment by pjz** [comment]
Okay, that's fine, like I said, just also get rid of the `extra_options` stuff near the end of the file.

**Comment by whit537** [comment]
How about the `ignoreprefix='python'`, do we still need that?

**Comment by whit537** [comment]
Looks like `ignoreprefix="python"` is a separate issue:

https://github.com/gratipay/aspen-python/issues/190#issuecomment-19290858

**Comment by pjz** [comment]
Right, leave that.

**Comment by pjz** [comment]
Okay, so looking at this again, you're doing a bunch of stuff in this set of commits:

  * updating dependencies
  * inside-virtualenv detection
  * renaming a bunch of things: aspen->deps, etc
  * switching from --python to using sys.executable

Ideally you would rebase/reorg the commits into 4 commits each of which did just one of those things.  Here in the real world where no one will really see it, it's probably fine as long as it passes CI.

**Comment by whit537** [comment]
@pjz The commits are actually pretty well-factored along those lines, modulo the first two and last two.

**Comment by whit537** [comment]
Anyway, Travis is green. :)

**Pull request merged**
