### PR TITLE
Add AppVeyor build status for master (fixes #484)

### LINKED ISSUE #484: Add links to AppVeyor status
To http://aspen.io/ and to GitHub page. This requires API key and I don't know where to get it.

### PR DESCRIPTION
**Pull request by techtonik**
Fixes #484.

### CODE REVIEW

**Comment by pjz** [comment]
Seems silly to add Appveyor but not Travis status.

**Comment by techtonik** [comment]
Working on it.

**Comment by pjz** [comment]
Might as well take care of https://github.com/gratipay/inside.gratipay.com/issues/307 too.

**Comment by techtonik** [comment]
Ready for review.

**Comment by whit537** [comment]
I believe #482 obviates this, yes?

**Comment by pjz** [comment]
I agree.

**Pull request closed without merging**
