### PR TITLE
implement Windows CI

### LINKED ISSUE #442: set up CI for Windows
Travis doesn't offer CI for Windows. Looks like our best bet is [AppVeyor](http://www.appveyor.com/). I've signed up for an account there.

### PR DESCRIPTION
**Pull request by whit537**
Closes #442.

### CODE REVIEW

**Comment by whit537** [comment]
So far so good!

screen shot 2015-06-18 at 9 09 42 am

screen shot 2015-06-18 at 9 10 47 am

**Comment by pjz** [comment]
Can you add a link to the appveyor status on the main aspen.io page?

**Comment by whit537** [comment]
Sure, maybe once we get the tests at least running (if not passing)?

**Comment by whit537** [comment]
Added to Roadmap (#357).

**Comment by techtonik** [comment]
Better test without SDKs to ensure we're not using any modules that need to be compiled.

**Comment by pjz** [comment]
PRs accepted!

**Pull request merged**
