### PR TITLE
fix simplate scoping

### LINKED ISSUE #462: functions in simplates behave unintuitively wrt scope
Introduced in #427.

This fails:

```python
bar = 'baz'
def foo()
    return bar
[---] text/html
```

This succeeds:

```python
bar = 'baz'
def foo()
    global bar
    return bar
[---] text/html
{{ foo() }}
```

### PR DESCRIPTION
**Pull request by whit537**
Fixes #462.

### CODE REVIEW

**Comment by whit537** [comment]
I tested the 0.40 upgrade branch on Gratipay with this PR, and it fixes the issues that I had worked around. There are some more issues that I thought were related but which this PR doesn't fix.

**Comment by whit537** [comment]
Ping @pjz.

**Comment by Changaco** [comment]
Looks okay. With this PR simplates don't modify `state` at all by default, all changes have to be done explicitly.

**Comment by whit537** [comment]
!m @Changaco @pjz

**Pull request merged**
