### PR TITLE
Fix Website API call in aspen.wsgi

### PR DESCRIPTION
**Pull request by whit537**
Regression in #455.

Ping @pjz. http://aspen.io/ is 500 due to this.

### CODE REVIEW

**Comment by whit537** [comment]
Travis is green. Proceeding since the change is trivial and the site is down ...

**Comment by pjz** [comment]
Did you happen to grep for Website while you were at it?

**Comment by pjz** [comment]
Did you happen to grep for Website while you were at it?

**Comment by whit537** [comment]
Not at the time but just did. No more case of same jumping out at me.

**Pull request merged**
