### PR TITLE
Document Dispatch{Status,Result} better

### LINKED ISSUE #468: DispatchResult need docs
https://github.com/gratipay/aspen-python/blob/master/aspen/dispatcher.py#L57

It is not clear what is `status match wildcards detail extra constrain_path`.

### PR DESCRIPTION
**Pull request by pjz**
Fix #468

### CODE REVIEW

**Comment by whit537** [comment]
On :fire:, I tell you!

**Comment by whit537** [comment]
lgtm when AppVeyor goes green.

**Comment by pjz** [comment]
I think we broke Appveyor.  They're under the @gratipay-gremlin right? Can you/it go poke the queue there and see what's up? Or maybe we just ran out of builds for the day or something.

**Comment by whit537** [comment]
Poked, and I've added you as a "collaborator" on the account.

**Comment by techtonik** [comment]
!m @pjz

**Pull request merged**
