### PR TITLE
fold Aspen's security program into Gratipay's

### PR DESCRIPTION
**Pull request by whit537**
[HackerOne](https://hackerone.com/gratipay) is nice.

### CODE REVIEW

**Comment by whit537** [comment]
I've listed Aspen in the scope on https://hackerone.com/gratipay, and I've invited @pjz to the team over there on HackerOne.

**Comment by whit537** [comment]
Lousy diff on `security.txt`. :-/

**Comment by pjz** [comment]
:+1: so if you rebase it on master you can merge.

**Comment by whit537** [comment]
Now a cleaner diff. Waiting for Travis ...

**Pull request merged**
